springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  time:
    storage-zone: UTC
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8081,http://localhost:19006}
