package team.soma.teto.health.global.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.parameters.HeaderParameter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI openAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Health Server API")
                        .description("AI-assisted PAPS fitness management backend API")
                        .version("0.0.1"))
                .components(new Components()
                        .addParameters(CorrelationIdFilter.CORRELATION_ID_HEADER, new HeaderParameter()
                                .name(CorrelationIdFilter.CORRELATION_ID_HEADER)
                                .description("Request correlation ID. UUID is generated by the server when omitted.")
                                .required(false)));
    }
}
